./monte_benchmark.sh >> sim_lock_test_results.txt
./monte_benchmark.sh >> sim_lock_test_results.txt
./monte_benchmark.sh >> sim_lock_test_results.txt
./monte_benchmark.sh >> sim_lock_test_results.txt
./monte_benchmark.sh >> sim_lock_test_results.txt
./monte_benchmark.sh >> sim_lock_test_results.txt
./monte_benchmark.sh >> sim_lock_test_results.txt
./monte_benchmark.sh >> sim_lock_test_results.txt
./monte_benchmark.sh >> sim_lock_test_results.txt
./monte_benchmark.sh >> sim_lock_test_results.txt
